# -*- coding: utf-8 -*-
"""Network_Anomaly_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZ5gKGak9kDr7vm57mRui4c7JfosEptq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.svm import OneClassSVM

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

# Suppress TensorFlow logging for cleaner output
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

def main():
    # ==========================================
    # 1. LOAD DATA
    # ==========================================
    column_names = [
        "duration","protocol_type","service","flag","src_bytes",
        "dst_bytes","land","wrong_fragment","urgent","hot",
        "num_failed_logins","logged_in","num_compromised","root_shell",
        "su_attempted","num_root","num_file_creations","num_shells",
        "num_access_files","num_outbound_cmds","is_host_login",
        "is_guest_login","count","srv_count","serror_rate",
        "srv_serror_rate","rerror_rate","srv_rerror_rate",
        "same_srv_rate","diff_srv_rate","srv_diff_host_rate",
        "dst_host_count","dst_host_srv_count","dst_host_same_srv_rate",
        "dst_host_diff_srv_rate","dst_host_same_src_port_rate",
        "dst_host_srv_diff_host_rate","dst_host_serror_rate",
        "dst_host_srv_serror_rate","dst_host_rerror_rate",
        "dst_host_srv_rerror_rate","label"
    ]

    print("Loading FULL KDD Cup 99 Dataset... (This may take a while)")
    try:
        train_data = pd.read_csv("kddcup.data.corrected", names=column_names)
        test_data = pd.read_csv("corrected", names=column_names)
    except FileNotFoundError:
        print("Error: Could not find the KDD Cup datasets.")
        return

    print(f"Total Training Rows: {train_data.shape[0]}")
    print(f"Total Testing Rows: {test_data.shape[0]}")

    # ==========================================
    # 2. PREPROCESSING
    # ==========================================
    print("Preprocessing Data...")
    train_data['label'] = train_data['label'].apply(lambda x: 0 if x == 'normal.' else 1)
    test_data['label'] = test_data['label'].apply(lambda x: 0 if x == 'normal.' else 1)

    encoder = LabelEncoder()
    for col in ['protocol_type', 'service', 'flag']:
        train_data[col] = encoder.fit_transform(train_data[col])
        test_data[col] = test_data[col].apply(lambda x: encoder.transform([x])[0] if x in encoder.classes_ else -1)

    X_train = train_data.drop('label', axis=1)
    y_train = train_data['label']
    X_test = test_data.drop('label', axis=1)
    y_test = test_data['label']

    print("Scaling Features...")
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Create a subset of ONLY normal traffic for our semi-supervised models
    X_train_normal = X_train_scaled[y_train == 0]

    results = []

    # ==========================================
    # 3. MODEL 1: RANDOM FOREST (Supervised)
    # ==========================================
    print("\n" + "="*40 + "\nTraining Random Forest...\n" + "="*40)
    rf = RandomForestClassifier(n_estimators=50, random_state=42, n_jobs=-1) # n_jobs=-1 uses all CPU cores
    rf.fit(X_train_scaled, y_train)
    rf_preds = rf.predict(X_test_scaled)

    rf_acc = accuracy_score(y_test, rf_preds)
    results.append(["Random Forest", rf_acc])
    print(f"Random Forest Accuracy: {rf_acc:.4f}")

    # ==========================================
    # 4. MODEL 2: ISOLATION FOREST (Unsupervised)
    # ==========================================
    print("\n" + "="*40 + "\nTraining Isolation Forest...\n" + "="*40)
    iso = IsolationForest(contamination=0.2, random_state=42, n_jobs=-1)
    iso.fit(X_train_scaled)

    iso_preds_raw = iso.predict(X_test_scaled)
    iso_preds = [1 if x == -1 else 0 for x in iso_preds_raw]

    iso_acc = accuracy_score(y_test, iso_preds)
    results.append(["Isolation Forest", iso_acc])
    print(f"Isolation Forest Accuracy: {iso_acc:.4f}")

    # ==========================================
    # 5. MODEL 3: ONE-CLASS SVM (Semi-supervised)
    # ==========================================
    print("\n" + "="*40 + "\nTraining One-Class SVM... (WARNING: This may take hours/days)\n" + "="*40)
    ocsvm = OneClassSVM(kernel='rbf', gamma='scale', nu=0.05)

    # NOW TRAINING ON ALL NORMAL DATA
    ocsvm.fit(X_train_normal)

    svm_preds_raw = ocsvm.predict(X_test_scaled)
    svm_preds = [1 if x == -1 else 0 for x in svm_preds_raw]

    svm_acc = accuracy_score(y_test, svm_preds)
    results.append(["One-Class SVM", svm_acc])
    print(f"One-Class SVM Accuracy: {svm_acc:.4f}")

    # ==========================================
    # 6. MODEL 4: AUTOENCODER (Deep Learning)
    # ==========================================
    print("\n" + "="*40 + "\nTraining Autoencoder...\n" + "="*40)
    input_dim = X_train_scaled.shape[1]
    input_layer = Input(shape=(input_dim,))

    encoded = Dense(16, activation="relu")(input_layer)
    encoded = Dense(8, activation="relu")(encoded)

    decoded = Dense(16, activation="relu")(encoded)
    decoded = Dense(input_dim, activation="linear")(decoded)

    autoencoder = Model(inputs=input_layer, outputs=decoded)
    autoencoder.compile(optimizer='adam', loss='mse')

    print("Training neural network on normal traffic...")
    # Increased batch size to 1024 to speed up training on massive datasets
    autoencoder.fit(X_train_normal, X_train_normal, epochs=10, batch_size=1024, validation_split=0.1, verbose=1)

    print("Calculating reconstruction thresholds...")
    reconstructions = autoencoder.predict(X_train_normal, batch_size=1024)
    mse = np.mean(np.power(X_train_normal - reconstructions, 2), axis=1)
    threshold = np.percentile(mse, 95)

    print("Evaluating Test Data...")
    test_reconstructions = autoencoder.predict(X_test_scaled, batch_size=1024)
    test_mse = np.mean(np.power(X_test_scaled - test_reconstructions, 2), axis=1)

    ae_preds = [1 if e > threshold else 0 for e in test_mse]

    ae_acc = accuracy_score(y_test, ae_preds)
    results.append(["Autoencoder", ae_acc])
    print(f"Autoencoder Accuracy: {ae_acc:.4f}")

    # ==========================================
    # 7. MODEL COMPARISON
    # ==========================================
    results_df = pd.DataFrame(results, columns=["Model", "Accuracy"])
    print(f"\n{'='*40}\nFINAL MODEL COMPARISON\n{'='*40}")
    print(results_df.sort_values(by="Accuracy", ascending=False).to_string(index=False))

    plt.figure(figsize=(10,6))
    sns.barplot(x="Accuracy", y="Model", data=results_df.sort_values(by="Accuracy", ascending=False), palette="magma")
    plt.title("Anomaly Detection Models Accuracy Comparison (Full Dataset)")
    plt.xlabel("Accuracy")
    plt.ylabel("Model")
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    main()